{"uuid":"8d7ca468-38ab-4918-8f29-870adb2915b1","historyId":"e2d26938b9926a246145a4fd032ce67c","fullName":"org.iti.tests.LoginTest.testLogin","labels":[{"name":"package","value":"org.iti.tests.LoginTest"},{"name":"testClass","value":"org.iti.tests.LoginTest"},{"name":"testMethod","value":"testLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"testautomationFramework"},{"name":"subSuite","value":"org.iti.tests.LoginTest"},{"name":"host","value":"DESKTOP-4OFQGQ7"},{"name":"thread","value":"45140@DESKTOP-4OFQGQ7.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"critical"}],"links":[],"name":"testLogin","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.ArrayIndexOutOfBoundsException: 2","trace":"java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:767)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:704)\r\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)\r\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:904)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\r\n\tat org.testng.TestRunner.run(TestRunner.java:603)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\r\n\tat org.testng.TestNG.run(TestNG.java:1060)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.ArrayIndexOutOfBoundsException: 2\r\n\tat org.iti.utils.Reader.getExcelData(Reader.java:34)\r\n\tat org.iti.utils.ProviderClass.getLoginData(ProviderClass.java:20)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)\r\n\t... 24 more\r\n"},"stage":"finished","description":"Verify that user can login successfully","steps":[],"attachments":[],"parameters":[],"start":1654084305813,"stop":1654084305816}